[package]
name = "librpm-sys"
description = "RPM Package Manager library FFI bindings (librpm.so)"
version.workspace = true
license = "MPL-2.0 AND LGPL-2.0-or-later"
authors.workspace = true
categories = ["external-ffi-bindings", "os"]
keywords.workspace = true
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/rpm-software-management/librpm.rs/tree/master/librpm-sys"
documentation = "https://docs.rs/crate/librpm-sys"
links = "rpm"
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
bindgen.workspace = true

[features]
# Enables bindings derived from RPM's build/macro.h, which is GPL-2.0-or-later.
rpmmacro = []
