/*
 * Copyright (C) RustRPM Developers
 *
 * Licensed under the Mozilla Public License Version 2.0
 * Fedora-License-Identifier: MPLv2.0
 * SPDX-2.0-License-Identifier: MPL-2.0
 * SPDX-3.0-License-Identifier: MPL-2.0
 *
 * This is free software.
 * For more information on the license, see LICENSE.
 * For more information on free software, see <https://www.gnu.org/philosophy/free-sw.en.html>.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at <https://mozilla.org/MPL/2.0/>.
 */

//! rpmsign library (i.e. `librpmsign.so`) FFI bindings
//!
//! Automatically generated by bindgen.
//!
//! This crate isn't intended to be used directly, but instead provides the
//! low-level binding which is used by the idiomatic librpm crate.

#![doc(html_root_url = "https://rustrpm.org/librpmsign_sys/")]
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

// Bindings to librpmsign.so
include!(concat!(env!("OUT_DIR"), "/binding.rs"));
