[package]
name = "librpmbuild-sys"
description = "rpmbuild library FFI bindings (librpmbuild.so)"
version.workspace = true
license = "MPL-2.0 AND GPL-2.0-or-later"
authors.workspace = true
categories = ["external-ffi-bindings", "os"]
keywords.workspace = true
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/rpm-software-management/librpm.rs/tree/master/librpmbuild-sys"
documentation = "https://docs.rs/crate/librpmbuild-sys"
edition.workspace = true
rust-version.workspace = true
links = "rpmbuild"

[build-dependencies]
bindgen.workspace = true
