[package]
name = "librpmbuild-sys"
description = "rpmbuild library FFI bindings (librpmbuild.so)"
version.workspace = true
license.workspace = true
authors.workspace = true
categories = ["external-ffi-bindings", "os"]
keywords.workspace = true
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/rpm-software-management/librpm.rs/tree/master/librpmbuild-sys"
documentation = "https://rustrpm.org/librpmbuild_sys/"
edition.workspace = true
rust-version.workspace = true
links = "rpmbuild"

[build-dependencies]
bindgen.workspace = true
