[package]
name = "librpmsign-sys"
description = "rpmsign library FFI bindings (librpmsign.so)"
version.workspace = true
license.workspace = true
authors.workspace = true
categories = ["external-ffi-bindings", "os"]
keywords.workspace = true
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/rpm-software-management/librpm.rs/tree/master/librpmsign-sys"
documentation = "https://docs.rs/crate/librpmsign-sys"
edition.workspace = true
rust-version.workspace = true
links = "rpmsign"

[build-dependencies]
bindgen.workspace = true
