/*
 * Copyright (C) RustRPM Developers
 *
 * Licensed under the Mozilla Public License Version 2.0
 * Fedora-License-Identifier: MPLv2.0
 * SPDX-2.0-License-Identifier: MPL-2.0
 * SPDX-3.0-License-Identifier: MPL-2.0
 *
 * This is free software.
 * For more information on the license, see LICENSE.
 * For more information on free software, see <https://www.gnu.org/philosophy/free-sw.en.html>.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at <https://mozilla.org/MPL/2.0/>.
 */

//! Rust binding for librpm: the RPM Package Manager library
//!
//! This crate contains idiomatic Rust bindings which aim to expose a safe
//! API to librpm. The low-level unsafe bindings are located in the
//! [librpm-sys] crate, which is automatically generated by bindgen.
//!
//! Call [`init`] (or [`init_with`] for custom configuration) before using
//! the library, then obtain a [`Db`] handle via [`Db::open`] to query the
//! RPM database.
//!
//! ## Logging
//!
//! By default, librpm logs to stderr using its native logging. Call
//! [`logging::set_behavior`] with [`LogBehavior::LogCrate`] to route
//! messages through Rust's [`log`] crate instead. Messages are emitted
//! with the target `"librpm"`.
//!
//! [`log`]: https://docs.rs/log
//! [librpm-sys]: https://rustrpm.org/librpm_sys/index.html

#![doc(html_root_url = "https://rustrpm.org/librpm/")]
#![warn(missing_docs, trivial_casts, unused_qualifications)]

use std::ffi::CStr;
use std::path::Path;

/// Error types (defined first due to macros)
#[macro_use]
pub mod error;

/// Archive (payload) extraction for RPM packages
pub mod archive;

/// RPM configuration (i.e. rpmrc)
mod config;

/// Logging bridge: routes librpm's C log output through Rust's `log` facade
pub mod logging;

/// Changelog information for RPM packages
pub mod changelog;

/// Dependency information for RPM packages
pub mod dep;

/// RPM database access
pub mod db;

/// File information for RPM packages
pub mod files;

/// Internal functionality not to be exposed outside of this crate
mod internal;

/// Macros are RPM's configuration system
pub mod macro_context;

/// RPM packages
pub mod package;

/// RPM version parsing and comparison
pub mod version;

/// RPM package signing (requires the `sign` feature)
#[cfg(feature = "sign")]
pub mod sign;

pub use self::{
    archive::ArchiveEntry, archive::PackageReader, changelog::ChangelogEntry, db::Db, db::Index,
    db::MatchMode, dep::DepFlags, dep::Dependencies, dep::Dependency, error::Error,
    files::FileAttrs, files::FileEntry, files::FileState, files::Files, logging::LogBehavior,
    logging::LogLevel, macro_context::MacroContext, package::PackageHeader, version::Version,
};

// Re-export types used in public API
pub use self::internal::rc::RpmErrorKind;
pub use self::internal::tag::Tag;
pub use self::internal::td::TagData;

/// Initialize librpm with default configuration.
///
/// This reads the system rpmrc and sets up the default database path.
/// Can only be called once per process.
pub fn init() -> Result<(), Error> {
    config::read_file(None)
}

/// Return the configured architecture name as RPM sees it (e.g. `"x86_64"`).
///
/// Returns `None` if librpm has not been initialized or the arch is not set.
pub fn arch() -> Option<&'static str> {
    let mut name: *const std::ffi::c_char = std::ptr::null();
    unsafe { librpm_sys::rpmGetArchInfo(&mut name, std::ptr::null_mut()) };
    if name.is_null() {
        return None;
    }
    Some(
        unsafe { CStr::from_ptr(name) }
            .to_str()
            .expect("arch name is not UTF-8"),
    )
}

/// Return the configured OS name as RPM sees it (e.g. `"linux"`).
///
/// Returns `None` if librpm has not been initialized or the OS is not set.
pub fn os() -> Option<&'static str> {
    let mut name: *const std::ffi::c_char = std::ptr::null();
    unsafe { librpm_sys::rpmGetOsInfo(&mut name, std::ptr::null_mut()) };
    if name.is_null() {
        return None;
    }
    Some(
        unsafe { CStr::from_ptr(name) }
            .to_str()
            .expect("os name is not UTF-8"),
    )
}

/// Initialize librpm with custom configuration.
///
/// Both arguments are optional:
/// - `config_file`: path to an rpmrc file (`None` for the system default)
/// - `db_path`: path to the RPM database (`None` for the default `_dbpath`)
///
/// Can only be called once per process.
pub fn init_with(config_file: Option<&Path>, db_path: Option<&Path>) -> Result<(), Error> {
    config::read_file(config_file)?;
    if let Some(path) = db_path {
        config::set_db_path(path)?;
    }
    Ok(())
}
