name: Compile and run tests

on: [push, pull_request]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    container: "quay.io/centos/centos:stream10"

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy

      - name: 📦 Install librpm dependencies
        run: |
          dnf install -y rpm-devel gcc clang-devel
          dnf -y clean all

      - name: 📎 Run Linters
        run: |
          cargo clippy --release -- -D warnings
          cargo fmt --all -- --check
          cargo doc --no-deps

      - name: 🔨 Build (Debug)
        run: cargo build --verbose

      - name: 🔨 Build (Release)
        run: cargo build --release --verbose

      - name: 🧪 Run Unit Tests
        run: cargo test --release --bins --lib

  integration-tests:
    strategy:
      matrix:
        container:
          - "quay.io/centos/centos:stream9"
          - "quay.io/centos/centos:stream10"
          - "registry.fedoraproject.org/fedora:latest"

    container: ${{ matrix.container }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - name: 📦 Install librpm dependencies
        run: |
          dnf install -y rpm-devel gcc clang-devel
          dnf -y clean all

      - name: 🧪 Run Integration Tests
        run: |
          cargo test --test '*' --release --all-features
